add a client to register endpoint to tks-info
sktelecom/tks-client pull request #3
Opened 2021-06-07 10:46 UTC by intelliguy

lma 설치용 workflow에서 사용할 binary 생성

2021-06-07 12:45 UTC, zugwan requested changes

2021-06-07 12:45 UTC, zugwan commented on cmd/register_endpoint.go
> +		"The list of endpoints like (application_type, endpoint) eg. {\"1\":\"192.168.5.55\",\"2\":\"192.168.5.55:10232\"}")
'192.168.5.55:10232'은 '192.168.5.55'의 오타일까요?
그리고 Endpoint라고 하면 'IP:Port' 가 한 쌍일텐데 지금 CLI 옵션은 IP와 포트가 나누어져 있어서 일반적인 형식은 아닌 거 같습니다. 특별한 이유가 있는지 궁금합니다.

2021-06-07 12:49 UTC, intelliguy commented on cmd/register_endpoint.go
> +		"The list of endpoints like (application_type, endpoint) eg. {\"1\":\"192.168.5.55\",\"2\":\"192.168.5.55:10232\"}")
이건 다양하게 적용할수 있도록 넣은 것입니다.
(https://github.com/openinfradev/decapod-flow/pull/30 도 참조)
1. 앱별 전체 url을 넣거나
2. 대표 ip 적고 포트별로 넣거나
3. 대표 ip만 적어서 default로 미리 정해진것 넣거나
위 세가지를 위한 것이고 일단 쓸것은 3번째 사용예입니다.

2021-06-07 12:58 UTC, intelliguy commented on cmd/register_endpoint.go
> +		"The list of endpoints like (application_type, endpoint) eg. {\"1\":\"192.168.5.55\",\"2\":\"192.168.5.55:10232\"}")
192.168.5.55는 192.168.5.55:80의 의도였습니다만 꼭 http가 아닐수도 있으니 한번 고려해봐야겠네요.

2021-06-08 01:30 UTC, jabbukka commented on cmd/register_endpoint.go
> +	appid := flag.String("appid", "", "Application ID of The endpoint. eg. 6abead61-ff2a-4af4-8f41-d2c44c745de7")
기존 appID가 appGroupID로 변경되어서 appid => appGroupID로 바뀌어야 할 것 같습니다.

2021-06-09 07:46 UTC, intelliguy commented on cmd/register_endpoint.go
> +	appid := flag.String("appid", "", "Application ID of The endpoint. eg. 6abead61-ff2a-4af4-8f41-d2c44c745de7")
반영했습니다.

2021-06-11 01:35 UTC, jabbukka approved these changes

2021-06-11 01:43 UTC, intelliguy commented on cmd/register_endpoint.go
> +		"The list of endpoints like (application_type, endpoint) eg. {\"1\":\"192.168.5.55\",\"2\":\"192.168.5.55:10232\"}")
이것도 수정했어요

2021-06-11 02:07 UTC, robertchoi80 commented on cmd/register_endpoint.go
> +	// - clusterep only: cluster endpoint and default endpoint using the node port. (currently prometheus)
주석 의미가 좀 혼동됩니다. ep 가 두개라는 것처럼 보여서..

2021-06-21 02:32 UTC, robertchoi80 commented on cmd/register_endpoint.go
> +	// - clusterep only: cluster endpoint and default endpoint using the node port. (currently prometheus)
걍 명확하게 default cluster endpoint 라고 해주심이..

2021-07-07 04:20 UTC, zugwan approved these changes

2021-07-07 04:20 UTC, merged